apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testwithrhtap-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testwithrhtap-2 
  name: testwithrhtap-2
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testwithrhtap-2 
    weight: 100 
  wildcardPolicy: None
